export const Jobdata = [
  {
    id: 1,
    type: 'job',
    time: "19 min ago",
    applied: "15",
    location: "Pune",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 2,
    type: 'job',
    time: "40 min ago",
    applied: "15", location: "Pune",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 3,
    type: 'job',
    time: "40 min ago",
    applied: "15", location: "Pune",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 4,
    type: 'job',
    time: "40 min ago",
    applied: "15", location: "Pune",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 5,
    type: 'job',
    time: "35 min ago",
    applied: "15", location: "Pune",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 6,
    type: 'job',
    time: "4 min ago",
    applied: "15", location: "Pune",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 7,
    type: 'job',
    time: "5 min ago",
    applied: "15", location: "Pune",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 8,
    type: 'job',
    time: "41 min ago",
    applied: "15", location: "Pune",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 9,
    type: 'job',
    time: "34 min ago",
    applied: "15", location: "Pune",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 10,
    type: 'job',
    time: "12 min ago",
    applied: "15", location: "Pune",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 11,
    type: 'job',
    time: "4 min ago",
    applied: "15", location: "Pune",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 12,
    type: 'job',
    time: "6 min ago", location: "Pune",
    applied: "15",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 13,
    type: 'job',
    time: "7 min ago",
    applied: "15", location: "Pune",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 14,
    type: 'job',
    time: "5 min ago",
    applied: "15",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left", location: "Pune",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 15,
    type: 'job',
    time: "8 min ago",
    applied: "15", location: "Pune",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workingdays: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
  {
    id: 17,
    type: 'job',
    time: "12 min ago",
    applied: "15",
    jobTitle: "CMC Strategy Associate II",
    company: "Pfizer",
    impressions: "15 impressions",
    daysleft: "11 days left", location: "Pune",
    deadline: "01 Mar 23, 11:59 PM IST",
    exprience: "3-4",
    salary: "not provided",
    workDetails: {
      workDetails: 6,
    },
    jobTiming: "Full Time",
    jobType: "Inoffice",
    eligibility: "Graduate",
    jobDescription: {
      responsibilities: [
        "Manage the preparation and maintenance of core dossiers for original applications, life cycle management and subsequent changes (moderate technical & regulatory complexity), coordinates Quality Query Responses to deficiency letters from Health Authorities, with the assistance of local and regional regulatory colleagues",
        "Functions as an individual or through project teams, utilizing technical or subject matter expertise to achieve desired results",
        "Provide adequate support and guidance to the team member(s) for authoring regulatory submissions and ensure effective data presentation and quality through effective review",
        "Author quality and timely CMC contributions for license maintenance activities such as US Annual Reports, Renewals, and other regulatory submissions under minimal/no supervision.",
        "Authors' key pieces of regulatory strategy and/ or submissions as delegated by the Product/ Project Lead(s) (additional to assigned products), on a need basis",
        "Negotiates submission data requirements and deliverable dates on a need basis",
        "Remain knowledgeable and maintains awareness about current regulations and guidance related to small molecule pharmaceuticals, Biologics, and Biosimilars, interprets, assesses its impact on product development programs and communicates to necessary stakeholders.",
      ],

      requirements: [
        "Minimum 1 to 3 Years of experience in the Pharmaceutical Industry with major experience in the Regulatory Affairs group handling new submissions and/or LCM submissions to global health authorities especially USFDA, EMA, and other EU authorities",
        "An understanding of global strategy and legislation that pertains to Small molecule Pharmaceuticals, Biologics and Biosimilars",
        "Experience in filing Sterile injectable submissions is preferable",
        "Good oral and written English communication skills",
        "Good conceptual, analytical, problem-solving, and organizational skills. An assertive, take-charge, proven manager with a strong result orientation, a positive “can do” attitude, and a sense of urgency to get things done",
        "Can make decisions to resolve moderately complex problems in standard situations. Makes decisions within guidelines, policies & procedures",
        "Can work independently in ambiguous situations as part of a work team",
        "Ability to comprehend and summarize complex technical data",
        "Ability to interpret global/regional CMC regulatory policies and requirements and guides the teams to apply them in their respective assigned projects",
        "High level of knowledge of general standards, processes, and policies of the Pfizer/ Pharmaceutical manufacturing Industry",
      ],
    },
  },
];
